<a href="https://colab.research.google.com/github/minhaz1172/NLP/blob/main/Word2Vec(Game_of_Thrones_dataset).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ** Gensim ** is an open source library in python that is used in unsupervised topic modelling and natural language processing. It is designed to extract semantic topics from documents. It can handle large text collections. Hence it makes it different from other machine learning software packages which target memory processing. Gensim also provides efficient multicore implementations for various algorithms to increase processing speed.

In [1]:
import numpy as np
import pandas as pd


In [2]:
pip install gensim

In [3]:
import gensim
print(gensim.__version__)

4.3.3


# import dataset from kaggle

In [4]:
from google.colab import files
files.upload()


Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"minhaz1172","key":"c20c43ca9e6e5be6fa69c912fab503c3"}'}

In [5]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [6]:
!pip install kaggle


# download

In [7]:
!kaggle datasets download -d khulasasndh/game-of-thrones-books

Dataset URL: https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books
License(s): unknown
  0% 0.00/3.71M [00:00<?, ?B/s]
100% 3.71M/3.71M [00:00<00:00, 688MB/s]


In [8]:
# unzip
!unzip game-of-thrones-books.zip -d got_books_data

Archive:  game-of-thrones-books.zip
  inflating: got_books_data/001ssb.txt  
  inflating: got_books_data/002ssb.txt  
  inflating: got_books_data/003ssb.txt  
  inflating: got_books_data/004ssb.txt  
  inflating: got_books_data/005ssb.txt  


# Read the text files

In [9]:
import gensim
import os
for filename in os.listdir("got_books_data"):
  if filename.endswith(".txt"):
    print(filename)

002ssb.txt
001ssb.txt
003ssb.txt
005ssb.txt
004ssb.txt


In [10]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [11]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
text=[]

for filename in os.listdir('got_books_data'):
  with open(os.path.join('got_books_data',filename), encoding='latin-1') as f:
    corpus=f.read()
    raw_sent=sent_tokenize(corpus)
    for sent in raw_sent:
      text.append(simple_preprocess(sent))

# also remove stopwords it will give better results

In [12]:
len(text)

145020

In [13]:
text

[['clash',
  'of',
  'kings',
  'book',
  'two',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'the',
  'comet',
  'tail',
  'spread',
  'across',
  'the',
  'dawn',
  'red',
  'slash',
  'that',
  'bled',
  'above',
  'the',
  'crags',
  'of',
  'dragonstone',
  'like',
  'wound',
  'in',
  'the',
  'pink',
  'and',
  'purple',
  'sky'],
 ['the',
  'maester',
  'stood',
  'on',
  'the',
  'windswept',
  'balcony',
  'outside',
  'his',
  'chambers'],
 ['it', 'was', 'here', 'the', 'ravens', 'came', 'after', 'long', 'flight'],
 ['their',
  'droppings',
  'speckled',
  'the',
  'gargoyles',
  'that',
  'rose',
  'twelve',
  'feet',
  'tall',
  'on',
  'either',
  'side',
  'of',
  'him',
  'hellhound',
  'and',
  'wyvern',
  'two',
  'of',
  'the',
  'thousand',
  'that',
  'brooded',
  'over',
  'the',
  'walls',
  'of',
  'the',
  'ancient',
  'fortress'],
 ['when',
  'first',
  'he',
  'came',
  'to',
  'dragonstone',
  'the',
  

# building wor2vec using gensim

## build a CBOW model
**in cbow model**
**min_count=1:** Includes words that appear at least once.<br>
**vector_size=100:** Generates word vectors of 100 dimensions.<br>
**window=5:** Considers a context window of 5 words before and after the target word.<br>
**sg=0**: Uses CBOW model (default setting).


In [14]:
model1=gensim.models.Word2Vec(text,vector_size=100,window=10,min_count=0,workers=os.cpu_count()) # windows 10 means context word both side of targe target is 10
# min_count means number of alphabet in words #


##  build a skip-gram model

In [15]:
model2=gensim.models.Word2Vec(text,min_count=1,vector_size=100,window=10,sg=1)

# Building Vocab
## for example for model1
## same also can be apllied to model 2 skip gram

In [16]:
model1.build_vocab(text)

In [17]:
model1.train(text, total_examples=model1.corpus_count, epochs=model1.epochs)
# total_examples =total senteces in corpus ,here corpus =text
# epochs =model1.epochs is how many iteration

(6602624, 8628190)

# finding most similar

In [18]:
model1.wv.most_similar('royce')

[('mallister', 0.8452393412590027),
 ('yohn', 0.8163731098175049),
 ('blackwood', 0.8151921629905701),
 ('vance', 0.8151821494102478),
 ('corbray', 0.8000307083129883),
 ('piper', 0.7928007245063782),
 ('hightower', 0.7890763282775879),
 ('locke', 0.7870227694511414),
 ('dayne', 0.7836257219314575),
 ('tytos', 0.7822970747947693)]

In [19]:
model1.wv.most_similar('hellbent')

[('smiler', 0.6496918201446533),
 ('myraham', 0.6446112394332886),
 ('dreary', 0.616868793964386),
 ('portside', 0.6158143877983093),
 ('ensnarled', 0.6152147650718689),
 ('longingly', 0.6131302714347839),
 ('sparked', 0.6129857301712036),
 ('trill', 0.6103412508964539),
 ('creak', 0.6091740727424622),
 ('breached', 0.6083506345748901)]

In [20]:
model1.wv.doesnt_match(['waymar',
  'had',
  'been',
  'sworn',
  'brother',
  'of',
  'the',
  'night',
  'watch'])

'of'

In [21]:
# see vector dimension of any
model1.wv['waymar']

array([ 0.07154883, -0.48147655,  0.30932516,  0.03670042,  0.17479862,
       -0.28492576,  0.01606521, -0.11149281, -0.31739622, -0.34090772,
       -0.13205183, -0.39947554,  0.01102133,  0.16696763, -0.18381819,
       -0.5248809 , -0.07593901, -0.01194962, -0.00350663, -0.22794235,
       -0.736531  , -0.33523467,  0.43396974, -0.29538658, -0.00711503,
        0.02957085, -0.16438185, -0.1627725 ,  0.13304375, -0.20408663,
        0.02209186, -0.28199154,  0.12859303, -0.3942764 , -0.49357978,
        0.35555854, -0.15770297, -0.47647566, -0.35421154, -0.52968425,
       -0.3018559 , -0.18649018, -0.48030585, -0.3217896 ,  0.27108014,
        0.10505092, -0.20843042, -0.05188667, -0.08474158,  0.1598356 ,
       -0.46544486,  0.2808295 , -0.30326113, -0.16152835,  0.1451714 ,
        0.10856659,  0.2910854 ,  0.06843411,  0.18599215, -0.23991317,
        0.11217682, -0.22340727,  0.22429198,  0.18096417,  0.12891345,
       -0.01519355,  0.07407975,  0.17934775, -0.4497965 ,  0.33

In [22]:
model1.wv['waymar'].shape # as we set vetor size =100

(100,)

In [23]:
# cheking similarity
model1.wv.similarity('robb','sansa')

0.4375741

# Get norm vector means get vector represetation of all word in text

In [24]:
model1.wv.get_normed_vectors()

array([[-0.03157167,  0.03329486,  0.07823748, ...,  0.00382698,
        -0.00795107, -0.10507463],
       [ 0.1367176 ,  0.07932004,  0.12713988, ...,  0.01543598,
        -0.00661222, -0.0411473 ],
       [-0.02581218,  0.04571579, -0.14877154, ...,  0.06430777,
        -0.17519535,  0.08006011],
       ...,
       [-0.13762678, -0.02540592, -0.09280737, ..., -0.02955442,
        -0.07511184, -0.02694174],
       [-0.16460258,  0.02910239, -0.01831856, ..., -0.01104243,
         0.18487741, -0.0165914 ],
       [-0.10214901, -0.06626577, -0.07598033, ...,  0.10627676,
        -0.10705455, -0.06241082]], dtype=float32)

In [25]:
model1.wv.get_normed_vectors().shape

(23476, 100)

In [26]:
y=model1.wv.index_to_key # vector to orginal word
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [27]:
len(y)

23476

# Dimension Reduction For better Performance
## now dimension=vector_size =100
## we will reduce dimension by PCA

In [28]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)# dimension=3

In [29]:
X=pca.fit_transform(model1.wv.get_normed_vectors())

In [30]:
X

array([[-0.37635154,  0.32535136, -0.04660852],
       [-0.26452783,  0.22695088,  0.0673493 ],
       [-0.71481246,  0.12862107, -0.03710156],
       ...,
       [-0.23325393,  0.02155638, -0.04921668],
       [-0.28485698,  0.1399754 , -0.27202874],
       [-0.59294325,  0.24163583,  0.12767816]], dtype=float32)

In [31]:
X.shape

(23476, 3)

# Plot 3D
## we will plot top 100 words and want to find simillarity ,distance from 3d plot
## use plotly express

In [42]:
import plotly.express as px
fig=px.scatter_3d(x=X[:100,0],y=X[:100,1],z=X[:100,2],text=y[:100],color=X[:100,0])
fig.update_traces(marker=dict(size=8))
fig.show()